server:
  port: 9092

spring:
           redis:
              host: 192.168.211.132
#              password: test
              port: 6379
              database: 0
              pool:
                  max-active: 8
                  max-wait: -1
                  max-idle: 20000
                  min-idle: 0
            timeout: 10000