server:
  port: 9098
 spring:
     thymeleaf:
             prefix: classpath:/WEB-INF/views/
             mode: HTML5
             encoding: UTF-8
             content-type: text/html
             cache: true

     datasource:
                    name: test_mysql
                    url: jdbc:mysql://localhost:3306/test_mysql?useUnicode=true&characterEncoding=UTF-8
                    username: root
                    password: root
                    type: com.alibaba.druid.pool.DruidDataSource
                    driver-class-name: com.mysql.jdbc.Driver
                    filters: stat
                    maxActive: 20
                    initialSize: 1
                    maxWait: 60000
                    minIdle: 1
                    timeBetweenEvictionRunsMillis: 60000
                    minEvictableIdleTimeMillis: 300000
                    validationQuery: select 'x'
                    testWhileIdle: true
                    testOnBorrow: false
                    testOnReturn: false
                    poolPreparedStatements: true
                    maxOpenPreparedStatements: 20