server:
  port: 9022
# smtp.163.com
spring:
  mail:
   host:  smtp.163.com #添加配置信息
   username: xxxxx@163.com
   password:     #设置密码，该处的密码是邮箱开启SMTP的授权码而非邮箱登陆密码
   default-encoding: UTF-8
   properties:
     mail:
       smtp:
         starttls:
            enable: true
            required: true
         auth: true   # 设置是否需要认证，如果为true,那么用户名和密码就必须的，
                       # 如果设置false，可以不设置用户名和密码，当然也得看你的对接的平台是否支持无密码进行访问的。
mail:
 fromMail:
   addr: xxxxx@163.com


   # STARTTLS[1]  是对纯文本通信协议的扩展。它提供一种方式将纯文本连接升级为加密连接（TLS或SSL），而不是另外使用一个端口作加密通信。