server:
  port: 9102

spring:
      http:
             converters:
               fastjson:
                 features: com.xphsc
      datasource:
        default:
              name: test_mysql
              url: jdbc:mysql://localhost:3306/activiti?useUnicode=true&characterEncoding=UTF-8
              username: root
              password: root
              type: com.alibaba.druid.pool.DruidDataSource
              driver-class-name: com.mysql.jdbc.Driver
              filters: stat
              maxActive: 20
              initialSize: 1
              maxWait: 60000
              minIdle: 1
              timeBetweenEvictionRunsMillis: 60000
              minEvictableIdleTimeMillis: 300000
              validationQuery: select 'x'
              testWhileIdle: true
              testOnBorrow: false
              testOnReturn: false
              poolPreparedStatements: true
              maxOpenPreparedStatements: 20

